apiVersion: v1
items:
- apiVersion: cluster.k8s.io/v1alpha1
  kind: Machine
  metadata:
    labels:
      set: master
    name: master-34.78.143.232
    namespace: weavek8sops
  spec:
    versions:
      kubelet: 1.16.11
    providerSpec:
      value:
        apiVersion: baremetalproviderspec/v1alpha1
        kind: BareMetalMachineProviderSpec
        private:
          address: 10.132.15.198
          port: 22
        public:
          address: 34.78.143.232
          port: 22
- apiVersion: cluster.k8s.io/v1alpha1
  kind: Machine
  metadata:
    labels:
      set: worker
    name: worker-35.241.163.64
    namespace: weavek8sops
  spec:
    versions:
      kubelet: 1.16.11
    providerSpec:
      value:
        apiVersion: baremetalproviderspec/v1alpha1
        kind: BareMetalMachineProviderSpec
        private:
          address: 10.132.15.204
          port: 22
        public:
          address: 35.241.163.64
          port: 22
kind: List
